jobs:
  build:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Pull Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./build/build

name: Run

on:
  schedule:
    - cron: "0 0/3 * * *"
